package com.hkbea.app.repositories;

import com.hkbea.app.domain.UserDat;
import com.hkbea.app.domain.UserDatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    long countByExample(UserDatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int deleteByExample(UserDatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int insert(UserDat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int insertSelective(UserDat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    List<UserDat> selectByExample(UserDatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    UserDat selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserDat record, @Param("example") UserDatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByExample(@Param("record") UserDat record, @Param("example") UserDatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByPrimaryKeySelective(UserDat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dat
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByPrimaryKey(UserDat record);
}