DROP TABLE IF EXISTS USER_DAT;
CREATE TABLE USER_DAT (
  ID       VARCHAR(200),
  NAME     VARCHAR(200),
  PASSWORD VARCHAR(200),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS FW_MENU;
CREATE TABLE FW_MENU (
  ID        VARCHAR(200),
  TEXT      VARCHAR(200),
  LEAF      VARCHAR(200),
  PARENT_ID VARCHAR(200),
  FORM_NAME VARCHAR(200),
  PRIMARY KEY (ID)
);
