package com.hkbea.odinfw.repositories;

import com.hkbea.odinfw.domain.FwMenu;
import com.hkbea.odinfw.domain.FwMenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FwMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    long countByExample(FwMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int deleteByExample(FwMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int insert(FwMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int insertSelective(FwMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    List<FwMenu> selectByExample(FwMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    FwMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") FwMenu record, @Param("example") FwMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByExample(@Param("record") FwMenu record, @Param("example") FwMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByPrimaryKeySelective(FwMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_menu
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    int updateByPrimaryKey(FwMenu record);
}