package com.hkbea.app.domain;

public class UserDat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dat.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dat.NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dat.PASSWORD
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dat.ID
     *
     * @return the value of user_dat.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dat.ID
     *
     * @param id the value for user_dat.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dat.NAME
     *
     * @return the value of user_dat.NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dat.NAME
     *
     * @param name the value for user_dat.NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dat.PASSWORD
     *
     * @return the value of user_dat.PASSWORD
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dat.PASSWORD
     *
     * @param password the value for user_dat.PASSWORD
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}