package com.hkbea.odinfw.domain;

import java.util.Objects;

public class FwMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_menu.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_menu.TEXT
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_menu.LEAF
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String leaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_menu.PARENT_ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_menu.FORM_NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    private String formName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_menu.ID
     *
     * @return the value of fw_menu.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_menu.ID
     *
     * @param id the value for fw_menu.ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_menu.TEXT
     *
     * @return the value of fw_menu.TEXT
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_menu.TEXT
     *
     * @param text the value for fw_menu.TEXT
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_menu.LEAF
     *
     * @return the value of fw_menu.LEAF
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_menu.LEAF
     *
     * @param leaf the value for fw_menu.LEAF
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_menu.PARENT_ID
     *
     * @return the value of fw_menu.PARENT_ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_menu.PARENT_ID
     *
     * @param parentId the value for fw_menu.PARENT_ID
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_menu.FORM_NAME
     *
     * @return the value of fw_menu.FORM_NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_menu.FORM_NAME
     *
     * @param formName the value for fw_menu.FORM_NAME
     *
     * @mbg.generated Thu Jun 28 14:30:39 CST 2018
     */
    public void setFormName(String formName) {
        this.formName = formName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FwMenu fwMenu = (FwMenu) o;
        return Objects.equals(id, fwMenu.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return text;
    }
}